config/routes.rb
Album::Application.routes.draw do

  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "users" => "users#index", :as=> "user_index"
  get "secret" => "home#secret", :as => "secret"

  match "about" => "info#about", :as => "about"
  match "contact" => "info#contact", :as => "contact"
  match "portfolio" => "info#portfolio", :as=> "port"  
  match "portfolio/:id" => "info#show_album", :as=> "show_album"

  resources :users
  resources :sessions
  resources :albums
  resources :photo
  resources :admin  
  root :to => 'photo#index'
    

    

end

app/models/albums.rb
class Albums < ActiveRecord::Base
  has_many :photo , :dependent => :destroy
end

app/models/photo.rb
class Photo < ActiveRecord::Base

#Attributes or fileds
  attr_accessible :image,:pic_name,:description,:albums_id

#associations
  belongs_to :albums
  
#carrier wave  
  mount_uploader :image,ImageUploader

#Validations
validates :description,:pic_name,:albums_id, :presence=>true
validates_uniqueness_of :pic_name
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :email
    validates_uniqueness_of :email     
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_filter :require_login

  def index
  end

 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :require_login
  
  def index
    @albums=Albums.all
  end
  
  def new
    @albums = Albums.new
  end

  def create
    
    @albums = Albums.new(params[:albums])
    if @albums.save
      
      redirect_to :action=>'index'
    else
      render  :action=>'new'
    end  
  end
  
  def show
    puts "****************ALBUM SHOW CALLED *******************"
    @albums=Albums.find(params[:id])
    @photo = Photo.where("albums_id=?",params[:id])
    
  end

  def edit
    
    @albums = Albums.find(params[:id])
  end

  def update
    
    @albums = Albums.find(params[:id])
    puts params[:albums]
    
    puts "************ ALBUMS UPDATE METHOD"
    
    if @albums.update_attributes(params[:albums])
      redirect_to :action=>'index'
    else
      render :action=>'edit'
    end
  
  end

  def destroy
    puts "************ ALBUMS DESTROY METHOD"
    puts params[:id]
    Albums.destroy(params[:id])
    redirect_to :action=>'index'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :require_login
  
  helper_method :current_users_list
    protected
    def current_users_list
      current_users.map {|u| u.email}.join(", ")
    end

def not_authenticated
  redirect_to :login, :alert => "Please login first."
end

end

app/controllers/info_controller.rb
class InfoController < ApplicationController

skip_before_filter :require_login

layout "application"

	def about
		
	end

	def contact
	end

	def portfolio
		@albums=Albums.all
		@photo=Photo.all
	end	

	

	def show_album
		puts "************ show album value"
		@albums = Albums.all
		@photo = Photo.where("albums_id=?",params[:id])
		puts @photo
		puts "************ show album value end"
		render :portfolio
	end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
skip_before_filter :require_login, :only=>[:index]

  def index
    @photo=Photo.all
  end

  def show
    @photo=Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def new
    @photo= Photo.new
    @albums=Albums.all
  end

  def create
    @photo = Photo.new(params[:photo])

    puts "***************" + @photo.inspect
    if @photo.save
      
      redirect_to :action=>'index'
    else
      render  :action=>'new'
    end
  end

  def update
    @photo = Photo.find(params[:id])
    puts '************** update ******************'
    puts params[:photo]
    if @photo.update_attributes(params[:photo])
      redirect_to :action=>'index'
    else
      render :action=>'edit'
    end
  end

  def destroy
    puts params[:id]
    Photo.destroy(params[:id])
    redirect_to :action=>'index'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_filter :require_login, :only=>[:new,:create]
  def new
  end
  
  def create
    user = login(params[:email],params[:password],params[:remember_me])
    if user
      redirect_back_or_to root_url,:notice => "Logged In"
    else
      flash.now.alert ="Email  or password is invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url,:notice=>"Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.find(:all)
  end
  
  def new
    puts "Inside User-NEW"
    @user = User.new
  end
  
  def create
    puts "Inside User-CREATE"
    @user = User.new(params[:user])
    if @user.save
      redirect_to :user_index, :notice=>"Signed Up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(params[:id])
    redirect_to :index
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<head>
<title>
	Admin
</title>
</head>
<div class="container">
	<%= render 'layouts/userAuth' %>
	
	<div class="row">
		<div class="span12 offset4">
			<div class="btn">
				<%= link_to "Manage Albums", :albums %>
			</div>
			<br><br>
			<div class="btn">
				<%= link_to "Manage Photos", :photo_index %>
			</div>
			<br><br>
			<div class="btn">
				<%= link_to "Manage Users", :user_index %>
			</div>
		</div>
		
	</div>
</div>

app/views/albums/edit.html.erb
<head>
<title>
	Edit Album
</title>
</head>
<div class="container">
	<%= form_for @albums do |f| %>
		<%= f.label :album_name%>
		<%= f.text_field :album_name%>
		
		<%= f.submit%>
		
			
		
	<%end%>
	<div class="btn-group">
		<div class="btn">
		<%= link_to 'Back',albums_index_path%>	
	</div>
	</div>	
	
</div>

app/views/albums/index.html.erb
<head>
	<title>
	Album Index
	</title>
</head>
<div class="container">
	<% @albums.each do |albums| %>
		<div class="clearfix">
			<span class="label"><%= albums.album_name%></span><br>
			<%if current_user %>
				<div class="btn-group">
					<div class="btn">
						<%= link_to 'Edit', edit_album_path(albums) %> 
					</div>	
					<div class="btn">
						<%= link_to 'Destroy', albums, confirm: 'Are you sure?', method: :delete%>
					</div>
					<div class="btn">
						<%= link_to 'Show', album_path(albums)%>	
					</div>	
				</div>	
			<% end %>
		</div>
		<br>
	<%end%>
	<p>
	
	<div class="btn-group">
		<div class="btn">
			<%= link_to 'Create New Album', new_album_path %>
		</div>
		<div class="btn">
			<%= link_to 'Back',admin_index_path%>	
		</div>
		
	</div>

	
	</p>
</div>

app/views/albums/new.html.erb
<head>
<title>
	Album New
</title>
</head>
<div class="container">
	<%= form_for @albums ,:url => { :action => "create" } do |f| %>
		<%= f.label :album_name%>
		<%= f.text_field :album_name%>
			<%= f.submit 'Submit'%>
				
	<%end%>
	<div class="btn">
		<%= link_to 'Back',albums_path%>	
	</div>	
</div>

app/views/albums/show.html.erb
<head>
<title>
	Album Show
</title>
</head>
<div class="container">
	<div class="row">
		<div class="span12 offset3">
			<%= @albums.album_name%>
		</div>	
	</div>
	<br>

	<ul class="thumbnails">
		<% @photo.each do |photo| %>
			<li class="span3">
				<%= image_tag photo.image_url, :width=>"220", :height=>"100"%><br>
				<%if current_user %>
					<%= link_to 'Edit', edit_photo_path(photo) %>
					<%= link_to 'Destroy', photo, confirm: 'Are you sure?', method: :delete%>
				<% end %>
			</li>
		<%end%>
	</ul>	
</div>

app/views/info/about.html.erb
<div class="container">
    
        
            <ul class="thumbnails">
                <li class="span3">
                    <%= image_tag("d1_bw.jpg",:width=>"250") %>
                </li>
                

                <li class="span8">
                    <div class="hero-unit">
                    <p>
                        <strong>Charlotte Photographer Deepti </strong>
                    </p>

                    <p>
                        It would not be wrong to say that photography is in my blood. I come from a family where my grandfather was a renowned cinmatographer in Marathi film industry.My uncle followed his footstep and joined the film industry as cinmatographer, while my own father and brother are in Still photography. 
                    </p>
                    <p>

                        It was in 2008 I got an opportunity to move to Charlotte,North Carolina US from San Francisco. This journey from the hip city, SF to Queen city, Charlotte came with a new blessing and I started as an amateur photographer doing photoshoot for friends and their families, the kaleidoscope within me started finding a new expression.
                    </p>
                    <p>
                        After many years as a keen amateur photographer, I decided to start a small  photography business. I realized that I enjoy working with kids and babies. It quickly became apparent that I was enjoying my part time job much more than I had anticipated and I decided that this was where my future lay. I decided to become a full time professional photographer.
                    </p>

                    <p>
                        My endeavor shall be to ensure that my clients shall enjoy working with me as much as I enjoy being behind the lenses.
                    </p>
                    <p>
                        I am currently based in Concord, North Carolina.You  could  get in touch with me for any of your  Photogrpahy needs like  Kids Portraits , Maternity Portraits, Family Portraits , Fashion Portraits,Senior Portraits. 
                    </p>
                    </div>
                </li>
                
               
                
            </ul>
        </div>
        
    

app/views/info/contact.html.erb
<head>
<title>Contact</title>
	</head>
<div class="container-fluid">
<ul class="thumbnails-fluid">
	<li class="span3-fluid">
		<div class="hero-unit">
			<%= image_tag("d3.jpg",:width=>"250") %>
		</div>	
	</li>

	<li class="span6">
		<div class="hero-unit">
		
			<br>MOBILE: +1(704) 490-6503
	      	<br>EMAIL: <a href="mailto:Depti8dec@gmail.com">Depti8dec@gmail.com</a>
		
		</div>	
	</div>
	</li>
</ul>
	
</div>

app/views/info/portfolio.html.erb
<head>

	<%= stylesheet_link_tag "prettyPhoto/css/prettyPhoto.css" %>
  	<%= javascript_include_tag "prettyPhoto/js/jquery.prettyPhoto.js" %>
  
  
</head>
<div class="container">
	<div class="row">
		<div class="span2">
			<% @albums.each do |album| %>
				<p>
				<div class="btn">
					<%= link_to album.album_name,show_album_path(album)%>
				</div>	
				</p>
			<%end%>
		</div>

		<div class="span10">
			<ul class="thumbnails">
				<% @photo.each do |photo| %>
					<li class="span3">
						<a rel="prettyPhoto[pp_gal]" href='<%= photo.image_url%>'>
							<%= image_tag photo.image_url , :width=>"200", :height=>"150"%>
						</a>	
					</li>						
				<%end%>
			</ul>
		</div>
	</div>
    

</div>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    $("a[rel^='prettyPhoto']").prettyPhoto();
  });
</script>

app/views/layouts/_header.html.erb
<div class="conatiner">
	
<div id="header-tabs">
	<div class="row">
		<div class="span12">
			<ul class="nav nav-tabs">
				<li><%= link_to "Home", '/' ,:class=>"alias"%></li>
				<li><%= link_to "About Me", :about ,:class=>"alias" %></li>
    			<li><%= link_to "Portfolio", :port ,:class=>"alias"%></li>
    			<li><%= link_to "Contact", :contact ,:class=>"alias"%></li>
				<%if current_user %>
        	  		<li><%= link_to "Logout", :logout ,:class=>"alias"%></li>
        		<%end%>
        		<li><div class="alias-name">Deepti Arora Photography </div></li>
				
        		
    		</ul>
		</div>
   		
	</div>
</div>
		
	
</div>


	

app/views/layouts/_userAuth.html.erb
<body class="<%= params[:controller] %>">
	
  <div id="container">
    
      <% if current_user %>
          
          <span class="label label-info">
           Welcome back  <%= current_user.email %>
          
          </span>
          <br><br>
      <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "Log in", login_path  %>.
      <% end %>
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    	<!-- Below code will display all the users that are currently logged in-->
      <!-- 
      <% if current_user %>
    	    <div id="current_users"> Currently active users: <%= current_users_list %></div>
    	<% end %>
    -->
    <%= yield %>
  </div>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag "bootstrap.css" %>
  
  
  <%= javascript_include_tag "application" %>
  
  
  <%= csrf_meta_tags %>
  <%= yield :mine%>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="row">
        <%= yield %>
      </div> 
  
  </body>
</html>

app/views/layouts/info.html.erb
<head>
  <title>Information</title>
  <%= stylesheet_link_tag    "info" %>
  <%= csrf_meta_tags %>

</head>
<body>
      <%= yield %>

</body>
</html>

app/views/photo/edit.html.erb
<head>
<title>
	Edit Photo
</title>
</head>
<div class="container">
	<%= form_for @photo do |f| %>
		<%= f.label :pic_name%>
		<%= f.text_field :pic_name%>

		<%= f.label :description%>
		<%= f.text_field :description%>
		
		<br>Album name  <br>
		<%= select("photo", "albums_id", Albums.all.collect {|a| [ a.album_name, a.id ] }, { :include_blank => true}) %><br>
		
		<%= f.submit%>
	<%end%>
</div>

app/views/photo/index.html.erb
<head>
	<%= stylesheet_link_tag "flexSlider/flexslider.css" %>
  	<%= javascript_include_tag "flexSlider/jquery.flexslider.js" %>
<title>
	Index
</title>
</head>
<div class="span1">
	<p>
		<%if current_user %>
			<div class="btn">
				<%= link_to 'New', new_photo_path %><br>
			</div>
			<br><br>
			<div class="btn">		
				<%= link_to 'Back', admin_index_path %>
			</div>	
		<%end%>
	</p>
</div>	

<div class="span10">
			
	<div class="index-body">
		<div class="flexslider">	
			<ul class="slides">
				<% @photo.each do |photo| %>
					<%if current_user %>
						<%= image_tag photo.image_url,:width=>"220", :height=>"100"%>
						<%= link_to 'Edit', edit_photo_path(photo) %>
						<%= link_to 'Destroy', photo, confirm: 'Are you sure?', method: :delete%>
					<% else %>
						<li>
							<%= image_tag photo.image_url%>
						</li>
					<%end%>
				<%end%>
			</ul>
		</div>
		<br/>
		
		<%if current_user %>
		
		<% else %>
			<script type="text/javascript">
				$(window).load(function() {
					$('.flexslider').flexslider({
						animation: "fade",//"fade" or "slide"
						slideDirection: "horizontal",   //"horizontal" or "vertical"
						slideshow: false,                //Animate slider automatically
						slideshowSpeed: 3000,           //slideshow cycling, in milliseconds
						animationDuration: 600,         //animations, in milliseconds
						directionNav: true,//navigation for previous/next navigation? (true/false)
						controlNav: true, //Create navigation for paging control of each clide? Note: Leave true for manualControls usage
						keyboardNav: false,//Allow slider navigating via keyboard left/right keys
						mousewheel: false,//Boolean: Allow slider navigating via mousewheel
						prevText: "Previous",//String: Set the text for the "previous" directionNav item
						nextText: "Next",//String: Set the text for the "next" directionNav item
						pausePlay: true,//Boolean: Create pause/play dynamic element
						pauseText: 'Pause',//String: Set the text for the "pause" pausePlay item
						playText: 'Play',//String: Set the text for the "play" pausePlay item
						randomize: false,//Boolean: Randomize slide order
						slideToStart: 0,//Integer: The slide that the slider should start on. Array notation (0 = first slide)
						animationLoop: true,//Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
						pauseOnAction: true,//Pause the slideshow when interacting with control elements, highly recommended.
						pauseOnHover: true,//Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
						controlsContainer: "",          //Selector: Declare which container the navigation elements should be appended too. Default container is the flexSlider element. Example use would be ".flexslider-container", "#container", etc. If the given element is not found, the default action will be taken.
						manualControls: "",             //Selector: Declare custom control navigation. Example would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
						start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
						before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
						after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
						end: function(){}               //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
					});
					});
			</script>
		<%end%>
	</div>
</div>

app/views/photo/new.html.erb
<head>
<title>
	Photo-New
</title>
</head>
<div class="container">
<%= form_for @photo ,:url => { :action => "create" }, :html=>{:multipart=>true}, :class=>'form-stacked' do |f| %>
	<% if @photo.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this user from being saved:</h2>

		<ul>
		  <% @photo.errors.full_messages.each do |msg| %>
		  		<li><%= msg %></li>
		  <% end %>
		</ul>
		    </div>
	<% end %>

	<div class="clearfix">
		
		<%= f.label :pic_name%>
		<%= f.text_field :pic_name, :class=> "input"%><br>
	</div>
	
	<div class="clearfix">
		<%= f.label :description%>
		<%= f.text_field :description, :class=> "input"%><br>
	</div>

	<div class="clearfix">
		<%= f.label :albums_id ,"Album Name"%>
		
		<%= select("photo", "albums_id", Albums.all.collect {|a| [ a.album_name, a.id ] }, { :include_blank => true },{:class=>"input"})%>
		<br>
	</div> 

	<div class="clearfix">
	<%= f.label :image ,"Image Name"%>
		<%= f.file_field :image, :class=> "input"%> 
	</div>
		<%= f.submit "Create new picture" ,:class=>'btn primary'%>
	
<%end%>
</div>

app/views/photo/show.html.erb
<%= @photo.pic_name%>

app/views/users/index.html.erb
<div class="container">
<% @users.each do |user|%>
	<%= user.email%>
	<%= link_to 'Edit', edit_user_path(user) %>&nbsp|&nbsp
	<%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete%>
	<br>
<%end%>

<%= link_to 'Add New User', new_user_path %><br>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>